### ISSUE TITLE
Not all data types are supported

### ISSUE THREAD

**Issue by guenp** [MotherDuck-Open-Source/duckdb-power-query-connector#5]
Right now, the connector supports the following `duckdb` data types:
- `bool`
- `int8`
- `int32`
- `float`
- `timestamp`

When trying to load any other types, Power BI may fail with an error:
```
This query does not have any columns with the supported data types
```

**Comment by kmatt** [comment]
@guenp First connection attempt succeeded! 

Do you need issues created when data type errors occur (have had one), or are those already part of the development plan?

**Comment by guenp** [comment]
@kmatt Great news, thanks for testing!
Can you please post them here? I'm adding more today.
I'm aiming to support all types in this list: https://duckdb.org/docs/sql/data_types/overview.html, I'm working my way down the list basically.
So far the only type I've found that won't fully work for data import is binary format, this currently not supported by Power BI (but it is supported by Power Query)

**Comment by guenp** [comment]
I've added the rest of the missing types so am going to close this issue.
There are some known bugs with `TIME`, `INTERVAL` and `TIMESTAMP WITH TIME ZONE`, but am tracking those separately in #7.
Also note that Power BI supports only a subset of the types supported by DuckDB and won't display binary formats like `UUID` and unsigned integers (see [Data types in Power BI Desktop](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-data-types)):
> The Binary data type isn't supported outside of the Power Query Editor. In the Power Query Editor, you can use the Binary data type when you load binary files if you convert it to other data types before loading it into the Power BI model. The Binary selection exists in the Data View and Report View menus for legacy reasons, but if you try to load Binary columns into the Power BI model, you might run into errors.

The latest release (.mez file) can be found [here](https://github.com/MotherDuck-Open-Source/duckdb-power-query-connector/releases).
@kmatt would be great you can give it a try and let me know if you still run into issues :) Thanks!

**Comment by kmatt** [comment]
@guenp I have not found which data type Power BI is complaining about here yet:

```
Feedback Type:
Frown (Error)

Error Message:
[Expression.Error] We cannot convert the specified value to the specified type.

Stack Trace:
Microsoft.Mashup.Host.Document.SerializedException
Microsoft.Mashup.Engine1.Runtime.ValueException: [Expression.Error] We cannot convert the specified value to the specified type.
   at Microsoft.Mashup.Evaluator.EvaluationHost.OnException(IEngineHost engineHost, IMessageChannel channel, ExceptionMessage message)
   at Microsoft.Mashup.Evaluator.MessageHandlers.TryDispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.MessageHandlers.Dispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.ChannelMessenger.ChannelMessageHandlers.TryDispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.MessageHandlers.Dispatch(IMessageChannel channel, Message message)
   at Microsoft.Mashup.Evaluator.Interface.IMessageChannelExtensions.WaitFor[T](IMessageChannel channel)
   at Microsoft.Mashup.Evaluator.RemotePreviewValueSource.PreviewValueSource.WaitFor(Func`1 condition, Boolean disposing)
   at Microsoft.Mashup.Evaluator.RemotePreviewValueSource.PreviewValueSource.get_Value()
   at Microsoft.Mashup.Evaluator.Interface.TracingPreviewValueSource.get_Value()
   at Microsoft.Mashup.Host.Document.Preview.PreviewEvaluation.<>c__DisplayClass22_0.<StartEvaluation>b__0(EvaluationResult2`1 result)

Stack Trace Message:
[Expression.Error] We cannot convert the specified value to the specified type.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass14_0.<HandleException>b__0()
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.Mashup.Client.UI.Shared.WebDialogs.WebDialog.<>c__DisplayClass79_0.<OnAjaxException>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Windows.DialogWindowBase.ShowModal(IWindowHandle windowHandle)
   at Microsoft.Mashup.Client.UI.Shared.WebDialogs.WebDialog.<>n__0(IWindowHandle owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.Mashup.Client.UI.Shared.Ux.FloatingDialog.NavigatorFloatingDialog.ShowEditLoad(IWindowHandle owner, ILegacyUIHost uiHost, Query query, ITelemetryService telemetryService, Boolean multiSelectionEnabledByDefault, ILearnedQueryImporterHost learnedQueryImporterHost, INavigatorSsoContextProvider ssoContextProvider)
   at Microsoft.PowerBI.Client.Windows.PowerBIDataImporter.ShowNavigator(Query query)
   at Microsoft.Mashup.Client.UI.Shared.DataImporter.ShowNavigatorOnSourceQuery(Query query, IEnumerable`1& importedQueries)
   at Microsoft.Mashup.Client.UI.Shared.DataImporter.ImportNavigationSource(Query query)
   at Microsoft.Mashup.Client.UI.Shared.DataImporter.OnGetPreviewResult(PreviewResult preview, Query query, String sourceID, String formulaTitle, Nullable`1 explicitImportDestination, Boolean isNewQuery, Boolean isFromEditor)
   at Microsoft.Mashup.Client.UI.Shared.DataImporter.GetPreviewResult(Query query, String sourceID, String formulaTitle, Boolean isNewQuery, Boolean isFromEditor, Nullable`1 explicitImportDestination)
   at Microsoft.Mashup.Client.UI.Shared.DataImporter.<>c__DisplayClass89_0.<OnQuerySettingsResolved>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass6_0.<RunApplication>b__0()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.RunApplication(String[] args)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)


PowerBINonFatalError:
{"AppName":"PBIDesktop","AppVersion":"2.126.1261.0","ModuleName":"","Component":"Microsoft.Mashup.Evaluator.EvaluationHost","Error":"Microsoft.Mashup.Engine1.Runtime.ValueException","MethodDef":"OnException","ErrorOffset":"","ErrorCode":""}

Snapshot Trace Logs:
C:\Users\mkeranen\Microsoft\Power BI Desktop Store App\FrownSnapShot39dce811-f420-4cd5-b038-a61759f5d821.zip

Model Default Mode:
Empty

Model Version:
PowerBI_V1

Performance Trace Logs:
C:\Users\mkeranen\Microsoft\Power BI Desktop Store App\PerformanceTraces.zip

Enabled Preview Features:
PBI_sparklines
PBI_scorecardVisual
PBI_NlToDax
PBI_fieldParametersSuperSwitch
PBI_backstageUI
PBI_setLabelOnExportPdf
PBI_dynamicFormatString
PBI_oneDriveSave
PBI_oneDriveShare
PBI_useModernPublishDialogs
PBI_newCard
PBI_buttonSlicerAuthoring
PBI_generateMeasureDescriptionsButton

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_qnaLiveConnect
PBI_b2bExternalDatasetSharing
PBI_enhancedTooltips
PBI_angularRls
PBI_onObject
PBI_gitIntegration
PBI_tmdlInDataset
PBI_EimLessElevatedUser
PBI_modelExplorer
PBI_daxQueryView
PBI_aiNarrativesVisual
PBI_qnaImproveLsdlCopilot
PBI_visualCalculationsAuthoring

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

PowerBIUserFeedbackServices_IsReported:
True

Formulas:


section Section1;

shared #"NavigatorBase_986d39e6-9ea2-4f43-878d-a8fbe5068f0a" = let
    Source = DuckDB.Contents("C:\Users\mkeranen\data\test\test.duckdb", null, [])
in
    Source;
```

**Comment by guenp** [comment]
Thanks @kmatt, this looks like a different error, `We cannot convert the specified value to the specified type.`, this is different from `This query does not have any columns with the supported data types`.

I tried creating some dummy columns with the types you listed, but I was able to import the data into Power BI without any errors. I tried both with DuckDB 0.9.2 and 0.10.0 and it worked fine. Below is the query I ran after running `duckdb test.db`:

```
create or replace table testtable AS (
    select
        '2024-02-01'::TIMESTAMP + interval 1 minute * (random() * 20000)::int as customer_timestamp,
        uuid()::VARCHAR as customer_varchar_field,
        (random() * 10)::INTEGER as customer_integer_field,
        (x * .1234)::DECIMAL(19, 2) as customer_decimal_field,
        (x * .1234)::DECIMAL(19, 4) as customer_decimal_field,
        '2024-03-14'::DATE as customer_date_field,
    from generate_series(1, 10) g(x)
);
```

Does the above work on your system? Is there anything I can change about the above query that reproduces your problem?

You're also welcome to join the [MotherDuck community slack](https://slack.motherduck.com/) and post on the #support channel there, I typically respond quicker there.

**Comment by guenp** [comment]
@kmatt I was able to reproduce the error! I'll create a new issue and link the repro steps there. Thank you for reporting 🙌

**Comment by kmatt** [comment]
> @kmatt I was able to reproduce the error! I'll create a new issue and link the repro steps there. Thank you for reporting 🙌

In anonymizing my example, I did remove underscores from the table name. Example now shows what the table name pattern in my use case is.
